version: '3'

services:
    mariadb:
        container_name: mariadb_container
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:mariadb-alpine
        env_file:
            - .env
        init: true
        restart: on-failure
        expose:
            - "3306" #default
        networks:
            - intra
        volumes:
            - /home/jischoi/data/db:/var/lib/mysql
        environment:
            - DB_NAME=${DB_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
            interval: 30s
            timeout: 10s
            retries: 3
    wordpress:
        container_name: wordpress_container
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:wordpress-alpine
        env_file:
            - .env
        init: true
        restart: on-failure
        volumes:
            - /home/jischoi/data/wp:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        depends_on:
            - mariadb
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_URL=${WORDPRESS_URL}
            - WORDPRESS_TITLE=${WORDPRESS_TITLE}
            - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
            - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
            - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
            - WORDPRESS_USER=${WORDPRESS_USER}
            - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
            - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
            - DB_NAME=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD} 
    nginx:
        container_name: nginx_container
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx:nginx-alpine
        env_file:
            - .env
        init: true # mariadb mysql daemon process will have PID 1 without this, then cannot manage signals correctly from host
        restart: on-failure # restart only if exit with non-zero code
        ports:
            - "443:443"
        volumes:
            - /home/jischoi/data/wp:/var/www/html
        networks:
            - intra
        depends_on:
            - wordpress

# volumes:
#     wp:
#         driver: local
#         driver_opts:
#                 type: none
#                 o: bind
#                 device: 'home/$user_name/data/wordpress'
#     db:
#         driver: local
#         drivar_opts:
#                 type: none
#                 o: bind
#                 device: 'home/$user_name/data/mariadb'

networks:
    intra:
        driver: bridge
