version: '3'

services:
    mariadb:
        container_name: mariadb_container
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        restart: always
        expose:
            - "3306"
        networks:
            - intra
        volumes:
            - /home/jischoi/data/db:/var/lib/mysql
        environment:
            - DB_NAME=${DB_NAME}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PW=${MARIADB_PW}
            - MARIADB_ROOT_PW=${MARIADB_ROOT_PW}
    wordpress:
        container_name: wordpress_container
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /home/jischoi/data/wp:/var/www/html
        expose:
            - "9000"
        networks:
            - intra
        depends_on:
            - mariadb
        environment:
            - ADMIN_USER=${ADMIN_USER}
            - ADMIN_USER_PW=${ADMIN_USER_PW}
            - AUTHOR_USER=${AUTHOR_USER}
            - AUTHOR_USER_PW=${AUTHOR_USER_PW} 
    nginx:
        container_name: nginx_container
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "443:443"
        volumes:
            - /home/jischoi/data/wp:/var/www/html
        networks:
            - intra
        depends_on:
            - wordpress

# volumes:
#     wp:
#         driver: local
#         driver_opts:
#                 type: none
#                 o: bind
#                 device: 'home/$user_name/data/wordpress'
#     db:
#         driver: local
#         drivar_opts:
#                 type: none
#                 o: bind
#                 device: 'home/$user_name/data/mariadb'

networks:
    intra:
        driver: bridge
